### ISSUE TITLE
Tag release

### ISSUE THREAD

**Issue by MichaelMackus** [eymengunay/EoHoneypotBundle#12]
Can we get a new tagged release? I just ran into this error 

```                                                                                                                          
  [Doctrine\Common\Annotations\AnnotationException]                                                                           
  [Semantical Error] The annotation "@Doctrine\ODM\MongoDB\Mapping\Annotations\Document" in class Eo\HoneypotBundle\Document  
  \HoneypotPrey does not exist, or could not be auto-loaded.                                                                  
```

Locking version against dev-master fixes.

**Comment by Falc** [comment]
This bundle do need more tag releases. I was using `dev-master` in an old project to benefit from some changes since v1.0.0 but some hours ago it started crashing because of the Symfony 3.0 support (#14).

Tagging https://github.com/eymengunay/EoHoneypotBundle/commit/c17675f2016fb167d919f3e4718660ab0ce35adc as v1.0.1 would be a good idea.

**Comment by eymengunay** [comment]
Thank you @Falc , I have tagged c17675f as [v1.0.1](https://github.com/eymengunay/EoHoneypotBundle/releases/tag/1.0.1)
